package pesoklp13.examples.tests.dummy

import org.springframework.boot.SpringBootConfiguration
import org.springframework.boot.autoconfigure.AutoConfigurationPackage

@SpringBootConfiguration
@AutoConfigurationPackage
class DummyTestsConfiguration